package fr.azur.auria.utils

import org.bukkit.Material
import org.bukkit.craftbukkit.enchantments.CraftEnchantment
import org.bukkit.enchantments.Enchantment
import org.bukkit.inventory.ItemStack
import org.bukkit.inventory.meta.EnchantmentStorageMeta

object EnchantBookModelData {
    private val enchantments = arrayOf(
        Triple(1, Enchantment.AQUA_AFFINITY, 1),
        Triple(2, Enchantment.BANE_OF_ARTHROPODS, 1),
        Triple(3, Enchantment.BANE_OF_ARTHROPODS, 2),
        Triple(4, Enchantment.BANE_OF_ARTHROPODS, 3),
        Triple(5, Enchantment.BANE_OF_ARTHROPODS, 4),
        Triple(6, Enchantment.BANE_OF_ARTHROPODS, 5),
        Triple(7, Enchantment.BLAST_PROTECTION, 1),
        Triple(8, Enchantment.BLAST_PROTECTION, 2),
        Triple(9, Enchantment.BLAST_PROTECTION, 3),
        Triple(10, Enchantment.BLAST_PROTECTION, 4),
        Triple(11, Enchantment.BREACH, 1),
        Triple(12, Enchantment.BREACH, 2),
        Triple(13, Enchantment.BREACH, 3),
        Triple(14, Enchantment.BREACH, 4),
        Triple(15, Enchantment.CHANNELING, 1),
        Triple(16, Enchantment.BINDING_CURSE, 1),
        Triple(17, Enchantment.VANISHING_CURSE, 1),
        Triple(18, Enchantment.DENSITY, 1),
        Triple(19, Enchantment.DENSITY, 2),
        Triple(20, Enchantment.DENSITY, 3),
        Triple(21, Enchantment.DENSITY, 4),
        Triple(22, Enchantment.DENSITY, 5),
        Triple(23, Enchantment.DEPTH_STRIDER, 1),
        Triple(24, Enchantment.DEPTH_STRIDER, 2),
        Triple(25, Enchantment.DEPTH_STRIDER, 3),
        Triple(26, Enchantment.EFFICIENCY, 1),
        Triple(27, Enchantment.EFFICIENCY, 2),
        Triple(28, Enchantment.EFFICIENCY, 3),
        Triple(29, Enchantment.EFFICIENCY, 4),
        Triple(30, Enchantment.EFFICIENCY, 5),
        Triple(31, Enchantment.FEATHER_FALLING, 1),
        Triple(32, Enchantment.FEATHER_FALLING, 2),
        Triple(33, Enchantment.FEATHER_FALLING, 3),
        Triple(34, Enchantment.FEATHER_FALLING, 4),
        Triple(35, Enchantment.FIRE_ASPECT, 1),
        Triple(36, Enchantment.FIRE_ASPECT, 2),
        Triple(37, Enchantment.FIRE_PROTECTION, 1),
        Triple(38, Enchantment.FIRE_PROTECTION, 2),
        Triple(39, Enchantment.FIRE_PROTECTION, 3),
        Triple(40, Enchantment.FIRE_PROTECTION, 4),
        Triple(41, Enchantment.FLAME, 1),
        Triple(42, Enchantment.FORTUNE, 1),
        Triple(43, Enchantment.FORTUNE, 2),
        Triple(44, Enchantment.FORTUNE, 3),
        Triple(45, Enchantment.FROST_WALKER, 1),
        Triple(46, Enchantment.FROST_WALKER, 2),
        Triple(47, Enchantment.IMPALING, 1),
        Triple(48, Enchantment.IMPALING, 2),
        Triple(49, Enchantment.IMPALING, 3),
        Triple(50, Enchantment.IMPALING, 4),
        Triple(51, Enchantment.IMPALING, 5),
        Triple(52, Enchantment.INFINITY, 1),
        Triple(53, Enchantment.KNOCKBACK, 1),
        Triple(54, Enchantment.KNOCKBACK, 2),
        Triple(55, Enchantment.LOOTING, 1),
        Triple(56, Enchantment.LOOTING, 2),
        Triple(57, Enchantment.LOOTING, 3),
        Triple(58, Enchantment.LOYALTY, 1),
        Triple(59, Enchantment.LOYALTY, 2),
        Triple(60, Enchantment.LOYALTY, 3),
        Triple(61, Enchantment.LUCK_OF_THE_SEA, 1),
        Triple(62, Enchantment.LUCK_OF_THE_SEA, 2),
        Triple(63, Enchantment.LUCK_OF_THE_SEA, 3),
        Triple(64, Enchantment.LURE, 1),
        Triple(65, Enchantment.LURE, 2),
        Triple(66, Enchantment.LURE, 3),
        Triple(67, Enchantment.MENDING, 1),
        Triple(68, Enchantment.MULTISHOT, 1),
        Triple(69, Enchantment.PIERCING, 1),
        Triple(70, Enchantment.PIERCING, 2),
        Triple(71, Enchantment.PIERCING, 3),
        Triple(72, Enchantment.PIERCING, 4),
        Triple(73, Enchantment.POWER, 1),
        Triple(74, Enchantment.POWER, 2),
        Triple(75, Enchantment.POWER, 3),
        Triple(76, Enchantment.POWER, 4),
        Triple(77, Enchantment.POWER, 5),
        Triple(78, Enchantment.PROJECTILE_PROTECTION, 1),
        Triple(79, Enchantment.PROJECTILE_PROTECTION, 2),
        Triple(80, Enchantment.PROJECTILE_PROTECTION, 3),
        Triple(81, Enchantment.PROJECTILE_PROTECTION, 4),
        Triple(82, Enchantment.PROTECTION, 1),
        Triple(83, Enchantment.PROTECTION, 2),
        Triple(84, Enchantment.PROTECTION, 3),
        Triple(85, Enchantment.PROTECTION, 4),
        Triple(86, Enchantment.PUNCH, 1),
        Triple(87, Enchantment.PUNCH, 2),
        Triple(88, Enchantment.QUICK_CHARGE, 1),
        Triple(89, Enchantment.QUICK_CHARGE, 2),
        Triple(90, Enchantment.QUICK_CHARGE, 3),
        Triple(91, Enchantment.RESPIRATION, 1),
        Triple(92, Enchantment.RESPIRATION, 2),
        Triple(93, Enchantment.RESPIRATION, 3),
        Triple(94, Enchantment.RIPTIDE, 1),
        Triple(95, Enchantment.RIPTIDE, 2),
        Triple(96, Enchantment.RIPTIDE, 3),
        Triple(97, Enchantment.SHARPNESS, 1),
        Triple(98, Enchantment.SHARPNESS, 2),
        Triple(99, Enchantment.SHARPNESS, 3),
        Triple(100, Enchantment.SHARPNESS, 4),
        Triple(101, Enchantment.SHARPNESS, 5),
        Triple(102, Enchantment.SILK_TOUCH, 1),
        Triple(103, Enchantment.SMITE, 1),
        Triple(104, Enchantment.SMITE, 2),
        Triple(105, Enchantment.SMITE, 3),
        Triple(106, Enchantment.SMITE, 4),
        Triple(107, Enchantment.SMITE, 4),
        Triple(108, Enchantment.SOUL_SPEED, 1),
        Triple(109, Enchantment.SOUL_SPEED, 2),
        Triple(110, Enchantment.SOUL_SPEED, 3),
        Triple(111, Enchantment.SWEEPING_EDGE, 1),
        Triple(112, Enchantment.SWEEPING_EDGE, 2),
        Triple(113, Enchantment.SWEEPING_EDGE, 3),
        Triple(114, Enchantment.SWIFT_SNEAK, 1),
        Triple(115, Enchantment.SWIFT_SNEAK, 2),
        Triple(116, Enchantment.SWIFT_SNEAK, 3),
        Triple(117, Enchantment.THORNS, 1),
        Triple(118, Enchantment.THORNS, 2),
        Triple(119, Enchantment.THORNS, 3),
        Triple(120, Enchantment.UNBREAKING, 1),
        Triple(121, Enchantment.UNBREAKING, 2),
        Triple(122, Enchantment.UNBREAKING, 3),
        Triple(123, Enchantment.WIND_BURST, 1),
        Triple(124, Enchantment.WIND_BURST, 2),
        Triple(125, Enchantment.WIND_BURST, 3),
        Triple(126, CraftEnchantment.stringToBukkit("auria:water_protection"), 1),
        Triple(127, CraftEnchantment.stringToBukkit("auria:water_protection"), 2),
        Triple(128, CraftEnchantment.stringToBukkit("auria:water_protection"), 3),
        Triple(129, CraftEnchantment.stringToBukkit("auria:water_protection"), 4)
    )

    fun applyModel(item: ItemStack) {
        if (item.type == Material.ENCHANTED_BOOK && !item.itemMeta.hasCustomModelData()) {
            val itemMeta = item.itemMeta
            if (itemMeta is EnchantmentStorageMeta) {
                val enchant = itemMeta.storedEnchants.entries.firstOrNull()
                val model = enchantments.find { triple ->
                    triple.second == enchant?.key && triple.third == enchant?.value
                }
                itemMeta.setCustomModelData(model?.first ?: 0)
                item.itemMeta = itemMeta
            }
        }
    }
}